In [2]:
import requests
import pandas as pd

In [3]:
from bs4 import BeautifulSoup as bs

In [4]:
url='https://www.worldometers.info/coronavirus/'

In [5]:
requests.get(url)

In [6]:
text_extractor= requests.get(url).text

In [25]:
#print(text_extractor)

In [8]:
soup=bs(text_extractor,'html.parser')

In [26]:
#print(soup)

In [10]:
table_find=soup.findAll('table',{'id':'main_table_countries_yesterday'})

In [27]:
#print(table_find)

In [12]:
table_find=table_find[0].findAll('tr')

In [28]:
#print(table_find)

In [14]:
complete_table=[]
for i in table_find:
    td_data=i.findAll('td')
    temp_data=[]
    if 'china' in str(td_data):
        continue
        
    for i in range(1,len(td_data)):
        temp=td_data[i].text
        if ',' in str(temp):
            temp=temp.replace(',','')
        if '+' in str(temp):
            temp=temp.replace('+','')
        if '\n' in str(temp):
            temp=temp.replace('\n','')
        if 'N/A' in str(temp):
            temp=temp.replace('N/A','0')    
        temp_data.append(temp)
        
    complete_table.append(temp_data)

In [15]:
complete_table[8:]

[['World',
  '704753890',
  '3959',
  '7010681',
  '57',
  '675619021',
  '14953',
  '22124188',
  '34791',
  '90413',
  '899.4',
  '',
  '',
  '',
  'All',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['USA',
  '111820082',
  '1151',
  '1219487                                ',
  '7',
  '109814428',
  '10109',
  '786167',
  '940',
  '333985',
  '3642',
  '1186851502',
  '3544901',
  '334805269 ',
  'North America',
  '3',
  '275',
  '0',
  '3',
  '0.02',
  '2348'],
 ['India',
  '45035393',
  '68',
  '533570                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '32016',
  '379',
  '935879495',
  '665334',
  '1406631776 ',
  'Asia',
  '31',
  '2636',
  '2',
  '0.05',
  '',
  '0.4'],
 ['France',
  '40138560',
  '',
  '167642                                ',
  '',
  '39970918',
  '',
  '0',
  '',
  '612013',
  '2556',
  '271490188',
  '4139547',
  '65584518 ',
  'Europe',
  '2',
  '391',
  '0',
  '',
  '',
  ''],
 ['Germany',
  '38828995',
  '73',
  '183027                                ',
  '16',
  '38240600',
  '',
  '405368',
  '0',
  '462891',
  '2182',
  '122332384',
  '1458359',
  '83883596 ',
  'Europe',
  '2',
  '458',
  '1',
  '0.9',
  '0.2',
  '4833'],
 ['Brazil',
  '38743918',
  '',
  '711380                                ',
  '',
  '36249161',
  '',
  '1783377',
  '0',
  '179908',
  '3303',
  '63776166',
  '296146',
  '215353593 ',
  'South America',
  '6',
  '303',
  '3',
  '',
  '',
  '8281'],
 ['S. Korea',
  '34571873',
  '',
  '35934                                ',
  '',
  '34535939',
  '',
  '0',
  '',
  '673523',
  '700',
  '15804065',
  '307892',
  '51329899 ',
  'Asia',
  '1',
  '1428',
  '3',
  '',
  '',
  ''],
 ['Japan',
  '33803572',
  '',
  '74694                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '269169',
  '595',
  '100414883',
  '799578',
  '125584838 ',
  'Asia',
  '4',
  '1681',
  '1',
  '',
  '',
  '95582'],
 ['Italy',
  '26723249',
  '',
  '196487                                ',
  '',
  '26361218',
  '',
  '165544',
  '22',
  '443445',
  '3261',
  '281126449',
  '4665010',
  '60262770 ',
  'Europe',
  '2',
  '307',
  '0',
  '',
  '',
  '2747'],
 ['UK',
  '24910387',
  '',
  '232112                                ',
  '',
  '24678275',
  '',
  '0',
  '0',
  '363666',
  '3389',
  '522526476',
  '7628357',
  '68497907 ',
  'Europe',
  '3',
  '295',
  '0',
  '',
  '',
  ''],
 ['Russia',
  '24124215',
  '',
  '402756                                ',
  '',
  '23545818',
  '',
  '175641',
  '0',
  '165454',
  '2762',
  '273400000',
  '1875095',
  '145805947 ',
  'Europe',
  '6',
  '362',
  '1',
  '',
  '',
  '1205'],
 ['Turkey',
  '17232066',
  '',
  '102174                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '201399',
  '1194',
  '162743369',
  '1902052',
  '85561976 ',
  'Asia',
  '5',
  '837',
  '1',
  '',
  '',
  '4024'],
 ['Spain',
  '13914811',
  '',
  '121760                                ',
  '',
  '13762417',
  '',
  '30634',
  '231',
  '297840',
  '2606',
  '471036328',
  '10082298',
  '46719142 ',
  'Europe',
  '3',
  '384',
  '0',
  '',
  '',
  '656'],
 ['Australia',
  '11853144',
  '664',
  '24414                                ',
  '',
  '11820014',
  '4299',
  '8716',
  '3',
  '454687',
  '937',
  '81916639',
  '3142326',
  '26068792 ',
  'Australia/Oceania',
  '2',
  '1068',
  '0',
  '25',
  '',
  '334'],
 ['Vietnam',
  '11625195',
  '',
  '43206                                ',
  '',
  '10640971',
  '',
  '941018',
  '',
  '117481',
  '437',
  '85826548',
  '867342',
  '98953541 ',
  'Asia',
  '9',
  '2290',
  '1',
  '',
  '',
  '9510'],
 ['Taiwan',
  '10241523',
  '',
  '19005                                ',
  '',
  '10222518',
  '',
  '0',
  '',
  '428720',
  '796',
  '30742304',
  '1286903',
  '23888595 ',
  'Asia',
  '2',
  '1257',
  '1',
  '',
  '',
  ''],
 ['Argentina',
  '10128845',
  '',
  '130841                                ',
  '',
  '9997258',
  '',
  '746',
  '',
  '220143',
  '2844',
  '35716069',
  '776264',
  '46010234 ',
  'South America',
  '5',
  '352',
  '1',
  '',
  '',
  '16'],
 ['Netherlands',
  '8635786',
  '',
  '22992                                ',
  '',
  '8612599',
  '',
  '195',
  '0',
  '501747',
  '1336',
  '25984435',
  '1509718',
  '17211447 ',
  'Europe',
  '2',
  '749',
  '1',
  '',
  '',
  '11'],
 ['Mexico',
  '7702809',
  '',
  '334958                                ',
  '',
  '6899865',
  '',
  '467986',
  '0',
  '58549',
  '2546',
  '20013810',
  '152124',
  '131562772 ',
  'North America',
  '17',
  '393',
  '7',
  '',
  '',
  '3557'],
 ['Iran',
  '7627186',
  '',
  '146811                                ',
  '',
  '0',
  '0',
  '0',
  '',
  '88665',
  '1707',
  '57320267',
  '666338',
  '86022837 ',
  'Asia',
  '11',
  '586',
  '2',
  '',
  '',
  '1199'],
 ['Indonesia',
  '6829221',
  '',
  '162063                                ',
  '',
  '6647104',
  '',
  '20054',
  '0',
  '24466',
  '581',
  '114158919',
  '408975',
  '279134505 ',
  'Asia',
  '41',
  '1722',
  '2',
  '',
  '',
  '72'],
 ['Poland',
  '6661991',
  '',
  '120598                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '176524',
  '3196',
  '39323709',
  '1041970',
  '37739785 ',
  'Europe',
  '6',
  '313',
  '1',
  '',
  '',
  '31941'],
 ['Colombia',
  '6400173',
  '',
  '143200                                ',
  '',
  '6212152',
  '',
  '44821',
  '342',
  '124244',
  '2780',
  '36951507',
  '717327',
  '51512762 ',
  'South America',
  '8',
  '360',
  '1',
  '',
  '',
  '870'],
 ['Greece',
  '6101379',
  '',
  '37869                                ',
  '',
  '0',
  '0',
  '0',
  '',
  '591412',
  '3671',
  '102228365',
  '9909078',
  '10316637 ',
  'Europe',
  '2',
  '272',
  '0',
  '',
  '',
  ''],
 ['Austria',
  '6081287',
  '',
  '22542                                ',
  '',
  '6054934',
  '',
  '3811',
  '',
  '670727',
  '2486',
  '211273524',
  '23302116',
  '9066710 ',
  'Europe',
  '1',
  '402',
  '0',
  '',
  '',
  '420'],
 ['Portugal',
  '5643062',
  '',
  '28126                                ',
  '',
  '5614809',
  '',
  '127',
  '61',
  '556484',
  '2774',
  '46139518',
  '4549993',
  '10140570 ',
  'Europe',
  '2',
  '361',
  '0',
  '',
  '',
  '13'],
 ['Ukraine',
  '5557995',
  '',
  '112418                                ',
  '',
  '5445577',
  '',
  '0',
  '',
  '128681',
  '2603',
  '32603805',
  '754855',
  '43192122 ',
  'Europe',
  '8',
  '384',
  '1',
  '',
  '',
  ''],
 ['Chile',
  '5384853',
  '1215',
  '64497                                ',
  '',
  '5252450',
  '',
  '67906',
  '7',
  '279730',
  '3350',
  '50382097',
  '2617225',
  '19250195 ',
  'South America',
  '4',
  '298',
  '0',
  '63',
  '',
  '3528'],
 ['Malaysia',
  '5278406',
  '',
  '37348                                ',
  '',
  '5233268',
  '',
  '7790',
  '11',
  '159079',
  '1126',
  '68580916',
  '2066869',
  '33181072 ',
  'Asia',
  '6',
  '888',
  '0',
  '',
  '',
  '235'],
 ['Canada',
  '4946090',
  '',
  '59034                                ',
  '',
  '4880962',
  '350',
  '6094',
  '99',
  '128843',
  '1538',
  '66572774',
  '1734189',
  '38388419 ',
  'North America',
  '8',
  '650',
  '1',
  '',
  '',
  '159'],
 ['Belgium',
  '4861695',
  '',
  '34376                                ',
  '',
  '4826748',
  '36',
  '571',
  '0',
  '416659',
  '2946',
  '37454182',
  '3209915',
  '11668278 ',
  'Europe',
  '2',
  '339',
  '0',
  '',
  '',
  '49'],
 ['Israel',
  '4841772',
  '',
  '12707                                ',
  '',
  '4798473',
  '',
  '30592',
  '0',
  '519169',
  '1363',
  '41373364',
  '4436346',
  '9326000 ',
  'Asia',
  '2',
  '734',
  '0',
  '',
  '',
  '3280'],
 ['DPRK',
  '4772813',
  '',
  '74                                ',
  '',
  '4772739',
  '',
  '0',
  '',
  '183636',
  '3',
  '',
  '',
  '25990679 ',
  'Asia',
  '5',
  '351225',
  '',
  '',
  '',
  ''],
 ['Thailand',
  '4770149',
  '',
  '34586                                ',
  '',
  '4692636',
  '',
  '42927',
  '0',
  '68069',
  '494',
  '17273454',
  '246488',
  '70078203 ',
  'Asia',
  '15',
  '2026',
  '4',
  '',
  '',
  '613'],
 ['Czechia',
  '4759041',
  '',
  '43517                                ',
  '',
  '4715206',
  '',
  '318',
  '2',
  '443246',
  '4053',
  '57834241',
  '5386552',
  '10736784 ',
  'Europe',
  '2',
  '247',
  '0',
  '',
  '',
  '30'],
 ['Peru',
  '4572667',
  '',
  '222161                                ',
  '',
  '4350506',
  '',
  '0',
  '4',
  '135751',
  '6595',
  '39010194',
  '1158115',
  '33684208 ',
  'South America',
  '7',
  '152',
  '1',
  '',
  '',
  ''],
 ['Switzerland',
  '4453053',
  '',
  '14452                                ',
  '',
  '4438309',
  '',
  '292',
  '0',
  '507549',
  '1647',
  '23833472',
  '2716487',
  '8773637 ',
  'Europe',
  '2',
  '607',
  '0',
  '',
  '',
  '33'],
 ['Philippines',
  '4140383',
  '',
  '66864                                ',
  '',
  '4067381',
  '',
  '6138',
  '0',
  '36800',
  '594',
  '36102746',
  '320888',
  '112508994 ',
  'Asia',
  '27',
  '1683',
  '3',
  '',
  '',
  '55'],
 ['South Africa',
  '4076463',
  '',
  '102595                                ',
  '',
  '3912506',
  '',
  '61362',
  '192',
  '67095',
  '1689',
  '26795090',
  '441027',
  '60756135 ',
  'Africa',
  '15',
  '592',
  '2',
  '',
  '',
  '1010'],
 ['Romania',
  '3529735',
  '',
  '68929                                ',
  '',
  '3459759',
  '',
  '1047',
  '21',
  '185470',
  '3622',
  '28758667',
  '1511122',
  '19031335 ',
  'Europe',
  '5',
  '276',
  '1',
  '',
  '',
  '55'],
 ['Denmark',
  '3183756',
  '',
  '8814                                ',
  '',
  '3174942',
  '',
  '0',
  '',
  '545636',
  '1511',
  '129333107',
  '22165247',
  '5834950 ',
  'Europe',
  '2',
  '662',
  '0',
  '',
  '',
  ''],
 ['Singapore',
  '3006155',
  '',
  '2024                                ',
  '',
  '3004131',
  '',
  '0',
  '4',
  '505785',
  '341',
  '24756666',
  '4165302',
  '5943546 ',
  'Asia',
  '2',
  '2937',
  '0',
  '',
  '',
  ''],
 ['Sweden',
  '2754129',
  '',
  '27407                                ',
  '',
  '2726472',
  '18',
  '250',
  '0',
  '269511',
  '2682',
  '19500873',
  '1908301',
  '10218971 ',
  'Europe',
  '4',
  '373',
  '1',
  '',
  '',
  '24'],
 ['New Zealand',
  '2621111',
  '',
  '5697                                ',
  '',
  '2613791',
  '',
  '1623',
  '',
  '535117',
  '1163',
  '7768604',
  '1586011',
  '4898203 ',
  'Australia/Oceania',
  '2',
  '860',
  '1',
  '',
  '',
  '331'],
 ['Serbia',
  '2615054',
  '69',
  '18057                                ',
  '',
  '2596608',
  '',
  '389',
  '',
  '302213',
  '2087',
  '13463733',
  '1555958',
  '8653016 ',
  'Europe',
  '3',
  '479',
  '1',
  '8',
  '',
  '45'],
 ['Iraq',
  '2465545',
  '',
  '25375                                ',
  '',
  '2439497',
  '',
  '673',
  '',
  '58474',
  '602',
  '19544451',
  '463523',
  '42164965 ',
  'Asia',
  '17',
  '1662',
  '2',
  '',
  '',
  '16'],
 ['Hungary',
  '2230232',
  '',
  '49048                                ',
  '',
  '2152155',
  '',
  '29029',
  '',
  '232164',
  '5106',
  '11394556',
  '1186160',
  '9606259 ',
  'Europe',
  '4',
  '196',
  '1',
  '',
  '',
  '3022'],
 ['Bangladesh',
  '2049377',
  '',
  '29493                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '12207',
  '176',
  '15254399',
  '90862',
  '167885689 ',
  'Asia',
  '82',
  '5692',
  '11',
  '',
  '',
  '-168.58'],
 ['Slovakia',
  '1877605',
  '',
  '21224                                ',
  '',
  '1856381',
  '',
  '0',
  '23',
  '343872',
  '3887',
  '7448789',
  '1364199',
  '5460193 ',
  'Europe',
  '3',
  '257',
  '1',
  '',
  '',
  ''],
 ['Georgia',
  '1861665',
  '',
  '17132                                ',
  '',
  '0',
  '0',
  '0',
  '',
  '469082',
  '4317',
  '16920079',
  '4263340',
  '3968738 ',
  'Asia',
  '2',
  '232',
  '0',
  '',
  '',
  '17130'],
 ['Jordan',
  '1746997',
  '',
  '14122                                ',
  '',
  '1731007',
  '',
  '1868',
  '59',
  '169597',
  '1371',
  '17201885',
  '1669945',
  '10300869 ',
  'Asia',
  '6',
  '729',
  '1',
  '',
  '',
  '181'],
 ['Ireland',
  '1734582',
  '',
  '9491                                ',
  '',
  '1724921',
  '',
  '170',
  '19',
  '345521',
  '1891',
  '13083449',
  '2606161',
  '5020199 ',
  'Europe',
  '3',
  '529',
  '0',
  '',
  '',
  '34'],
 ['Pakistan',
  '1581936',
  '',
  '30664                                ',
  '',
  '1538689',
  '',
  '12583',
  '',
  '6893',
  '134',
  '30589153',
  '133292',
  '229488994 ',
  'Asia',
  '145',
  '7484',
  '8',
  '',
  '',
  '55'],
 ['Finland',
  '1516117',
  '',
  '11958                                ',
  '',
  '1503975',
  '17',
  '184',
  '0',
  '272930',
  '2153',
  '12108977',
  '2179850',
  '5554960 ',
  'Europe',
  '4',
  '465',
  '0',
  '',
  '',
  '33'],
 ['Norway',
  '1509732',
  '',
  '6638                                ',
  '',
  '1503094',
  '',
  '0',
  '0',
  '273930',
  '1204',
  '11002430',
  '1996315',
  '5511370 ',
  'Europe',
  '4',
  '830',
  '1',
  '',
  '',
  ''],
 ['Kazakhstan',
  '1411831',
  '',
  '13848                                ',
  '',
  '1383020',
  '',
  '14963',
  '24',
  '73514',
  '721',
  '11575012',
  '602707',
  '19205043 ',
  'Asia',
  '14',
  '1387',
  '2',
  '',
  '',
  '779'],
 ['Lithuania',
  '1397806',
  '20',
  '9897                                ',
  '',
  '1387478',
  '33',
  '431',
  '0',
  '525154',
  '3718',
  '10540357',
  '3959997',
  '2661708 ',
  'Europe',
  '2',
  '269',
  '0',
  '8',
  '',
  '162'],
 ['Slovenia',
  '1356546',
  '',
  '7100                                ',
  '',
  '1349424',
  '',
  '22',
  '0',
  '652803',
  '3417',
  '2847701',
  '1370382',
  '2078034 ',
  'Europe',
  '2',
  '293',
  '1',
  '',
  '',
  '11'],
 ['Bulgaria',
  '1339851',
  '3',
  '38748                                ',
  '',
  '1292944',
  '',
  '8159',
  '22',
  '195753',
  '5661',
  '11671043',
  '1705147',
  '6844597 ',
  'Europe',
  '5',
  '177',
  '1',
  '0.4',
  '',
  '1192'],
 ['Croatia',
  '1309728',
  '',
  '18687                                ',
  '',
  '1258432',
  '',
  '32609',
  '',
  '322650',
  '4604',
  '5660084',
  '1394355',
  '4059286 ',
  'Europe',
  '3',
  '217',
  '1',
  '',
  '',
  '8033'],
 ['Guatemala',
  '1291293',
  '',
  '20289                                ',
  '',
  '1269891',
  '',
  '1113',
  '5',
  '69484',
  '1092',
  '7593848',
  '408622',
  '18584039 ',
  'North America',
  '14',
  '916',
  '2',
  '',
  '',
  '60'],
 ['Morocco',
  '1278992',
  '',
  '16303                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '33860',
  '432',
  '13001033',
  '344191',
  '37772756 ',
  'Africa',
  '30',
  '2317',
  '3',
  '',
  '',
  '173'],
 ['Lebanon',
  '1243838',
  '',
  '10952                                ',
  '',
  '1087587',
  '',
  '145299',
  '74',
  '186068',
  '1638',
  '4795578',
  '717380',
  '6684849 ',
  'Asia',
  '5',
  '610',
  '1',
  '',
  '',
  '21736'],
 ['Costa Rica',
  '1238883',
  '',
  '9428                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '239058',
  '1819',
  '4659757',
  '899158',
  '5182354 ',
  'North America',
  '4',
  '550',
  '1',
  '',
  '',
  '71154'],
 ['Bolivia',
  '1212131',
  '',
  '22407                                ',
  '',
  '1177145',
  '',
  '12579',
  '220',
  '101073',
  '1868',
  '2710261',
  '225993',
  '11992656 ',
  'South America',
  '10',
  '535',
  '4',
  '',
  '',
  '1049'],
 ['Tunisia',
  '1153361',
  '',
  '29423                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '95741',
  '2442',
  '5013383',
  '416164',
  '12046656 ',
  'Africa',
  '10',
  '409',
  '2',
  '',
  '',
  '1157'],
 ['Cuba',
  '1115251',
  '',
  '8530                                ',
  '',
  '1106660',
  '',
  '61',
  '',
  '98645',
  '754',
  '14402674',
  '1273936',
  '11305652 ',
  'North America',
  '10',
  '1325',
  '1',
  '',
  '',
  '5'],
 ['Ecuador',
  '1070188',
  '',
  '36043                                ',
  '',
  '1034145',
  '',
  '0',
  '',
  '59083',
  '1990',
  '3082403',
  '170173',
  '18113361 ',
  'South America',
  '17',
  '503',
  '6',
  '',
  '',
  ''],
 ['UAE',
  '1067030',
  '',
  '2349                                ',
  '',
  '0',
  '0',
  '0',
  '',
  '105837',
  '233',
  '200732262',
  '19910389',
  '10081785 ',
  'Asia',
  '9',
  '4292',
  '0',
  '',
  '',
  '1007'],
 ['Panama',
  '1059893',
  '',
  '8727                                ',
  '',
  '1051102',
  '',
  '64',
  '16',
  '238341',
  '1962',
  '7882622',
  '1772585',
  '4446964 ',
  'North America',
  '4',
  '510',
  '1',
  '',
  '',
  '14'],
 ['Uruguay',
  '1041111',
  '',
  '7664                                ',
  '',
  '1030944',
  '',
  '2503',
  '18',
  '297799',
  '2192',
  '6114822',
  '1749083',
  '3496016 ',
  'South America',
  '3',
  '456',
  '1',
  '',
  '',
  '716'],
 ['Mongolia',
  '1011496',
  '',
  '2284                                ',
  '',
  '1009212',
  '',
  '0',
  '0',
  '299429',
  '676',
  '4030048',
  '1193000',
  '3378078 ',
  'Asia',
  '3',
  '1479',
  '1',
  '',
  '',
  ''],
 ['Nepal',
  '1003450',
  '',
  '12031                                ',
  '',
  '991322',
  '',
  '97',
  '',
  '33199',
  '398',
  '6047766',
  '200088',
  '30225582 ',
  'Asia',
  '30',
  '2512',
  '5',
  '',
  '',
  '3'],
 ['Belarus',
  '994037',
  '',
  '7118                                ',
  '',
  '985592',
  '',
  '1327',
  '',
  '105381',
  '755',
  '13646641',
  '1446722',
  '9432800 ',
  'Europe',
  '9',
  '1325',
  '1',
  '',
  '',
  '141'],
 ['Latvia',
  '982505',
  '',
  '6715                                ',
  '',
  '971406',
  '',
  '4384',
  '',
  '531418',
  '3632',
  '7885792',
  '4265272',
  '1848837 ',
  'Europe',
  '2',
  '275',
  '0',
  '',
  '',
  '2371'],
 ['Saudi Arabia',
  '841469',
  '',
  '9646                                ',
  '',
  '0',
  '0',
  '0',
  '',
  '23475',
  '269',
  '45481735',
  '1268848',
  '35844909 ',
  'Asia',
  '43',
  '3716',
  '1',
  '',
  '',
  '109'],
 ['Paraguay',
  '837602',
  '',
  '20155                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '114648',
  '2759',
  '2657506',
  '363751',
  '7305843 ',
  'South America',
  '9',
  '362',
  '3',
  '',
  '',
  '16306'],
 ['Azerbaijan',
  '835234',
  '',
  '10400                                ',
  '',
  '824089',
  '',
  '745',
  '',
  '81089',
  '1010',
  '7748050',
  '752223',
  '10300205 ',
  'Asia',
  '12',
  '990',
  '1',
  '',
  '',
  '72'],
 ['Bahrain',
  '729549',
  '',
  '1574                                ',
  '',
  '727915',
  '',
  '60',
  '0',
  '408944',
  '882',
  '10948549',
  '6137138',
  '1783983 ',
  'Asia',
  '2',
  '1133',
  '0',
  '',
  '',
  '34'],
 ['Cyprus',
  '681110',
  '',
  '1365                                ',
  '',
  '679745',
  '',
  '0',
  '',
  '556741',
  '1116',
  '9640118',
  '7879860',
  '1223387 ',
  'Asia',
  '2',
  '896',
  '0',
  '',
  '',
  ''],
 ['Dominican Republic',
  '675890',
  '',
  '4384                                ',
  '',
  '671316',
  '',
  '190',
  '4',
  '61131',
  '397',
  '3740928',
  '338350',
  '11056370 ',
  'North America',
  '16',
  '2522',
  '3',
  '',
  '',
  '17'],
 ['Sri Lanka',
  '672754',
  '',
  '16897                                ',
  '',
  '655852',
  '',
  '5',
  '',
  '31181',
  '783',
  '6486117',
  '300619',
  '21575842 ',
  'Asia',
  '32',
  '1277',
  '3',
  '',
  '',
  '0.2'],
 ['Kuwait',
  '667158',
  '',
  '2570                                ',
  '',
  '0',
  '0',
  '0',
  '',
  '152308',
  '587',
  '8455743',
  '1930391',
  '4380326 ',
  'Asia',
  '7',
  '1704',
  '1',
  '',
  '',
  '993'],
 ['Myanmar',
  '641873',
  '',
  '19495                                ',
  '',
  '620159',
  '',
  '2219',
  '',
  '11622',
  '353',
  '11711514',
  '212061',
  '55227143 ',
  'Asia',
  '86',
  '2833',
  '5',
  '',
  '',
  '40'],
 ['Moldova',
  '635145',
  '',
  '12218                                ',
  '',
  '0',
  '0',
  '0',
  '0',
  '158265',
  '3044',
  '3216305',

In [16]:
df=pd.DataFrame(complete_table[8:])

In [30]:
df

,Country,Other Total,Cases New,Cases Total,Deaths New,Deaths Total,Recovered New,Recovered Active,Cases Serious,Critical Tot Cases,1M pop Deaths,1M pop Total,Tests Tests,1M pop Population
0,World,704753890,3959,7010681,57,675619021,14953,22124188,34791,90413,899.4,,,
1,USA,111820082,1151,1219487,7,109814428,10109,786167,940,333985,3642,1186851502,3544901,334805269
2,India,45035393,68,533570,,0,0,0,0,32016,379,935879495,665334,1406631776
3,France,40138560,,167642,,39970918,,0,,612013,2556,271490188,4139547,65584518
4,Germany,38828995,73,183027,16,38240600,,405368,0,462891,2182,122332384,1458359,83883596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,Total:,70200879,1215,1367332,,66683585,,2149962,8953,,,,,
233,Total:,14895771,664,33015,,14752388,,110368,31,,,,,
234,Total:,12860924,,258892,,12090808,,511224,529,,,,,
235,Total:,721,,15,,706,,0,0,,,,,
236,Total:,704753890,3959,7010681,57,675619021,14953,22124188,34791,90413.4,899.4,,,

In [18]:
df.drop([14,15,16,17,18,19,20],axis=1,inplace=True)

In [19]:
df.columns=(['Country','Other Total','Cases New','Cases Total','Deaths New','Deaths Total','Recovered New','Recovered Active','Cases Serious',
           'Critical Tot Cases','1M pop Deaths','1M pop Total','Tests Tests', '1M pop Population'])

In [20]:
df

,Country,Other Total,Cases New,Cases Total,Deaths New,Deaths Total,Recovered New,Recovered Active,Cases Serious,Critical Tot Cases,1M pop Deaths,1M pop Total,Tests Tests,1M pop Population
0,World,704753890,3959,7010681,57,675619021,14953,22124188,34791,90413,899.4,,,
1,USA,111820082,1151,1219487,7,109814428,10109,786167,940,333985,3642,1186851502,3544901,334805269
2,India,45035393,68,533570,,0,0,0,0,32016,379,935879495,665334,1406631776
3,France,40138560,,167642,,39970918,,0,,612013,2556,271490188,4139547,65584518
4,Germany,38828995,73,183027,16,38240600,,405368,0,462891,2182,122332384,1458359,83883596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,Total:,70200879,1215,1367332,,66683585,,2149962,8953,,,,,
233,Total:,14895771,664,33015,,14752388,,110368,31,,,,,
234,Total:,12860924,,258892,,12090808,,511224,529,,,,,
235,Total:,721,,15,,706,,0,0,,,,,
236,Total:,704753890,3959,7010681,57,675619021,14953,22124188,34791,90413.4,899.4,,,

In [21]:
df.to_csv('C:/Users/HP/Desktop/new folder/live project/wordometer_data.csv')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             237 non-null    object
 1   Other Total         237 non-null    object
 2   Cases New           237 non-null    object
 3   Cases Total         237 non-null    object
 4   Deaths New          237 non-null    object
 5   Deaths Total        237 non-null    object
 6   Recovered New       237 non-null    object
 7   Recovered Active    237 non-null    object
 8   Cases Serious       237 non-null    object
 9   Critical Tot Cases  237 non-null    object
 10  1M pop Deaths       237 non-null    object
 11  1M pop Total        237 non-null    object
 12  Tests Tests         237 non-null    object
 13  1M pop Population   237 non-null    object
dtypes: object(14)
memory usage: 26.1+ KB